{
 "title": "Métricas de RPi",
 "description": "Dashboard para múltiples Raspberry Pi",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instancia",
    "label": "RPi",
    "query": "label_values(node_uname_info, hostname)"
   }
  ]
 },
 "panels": [
  { "title": "Información del sistema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{hostname=\"$instancia\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Tamaño total de Disco",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\", hostname=\"$instancia\"}/1000000000"
    }
   ]
  },
  {
   "title": "Tamaño total de Memoria RAM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{hostname=\"$instancia\"}/1000/1000"
    }
   ]
  },
  { "title": "Métricas básicas del Sistema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Tiempo de actividad del sistema",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - node_boot_time_seconds{hostname=\"$instancia\"})/60/60"
    }
   ]
  },
  {
   "title": "uso de Disco",
   "type": "bargauge",
   "description": "Espacio total de disco junto con el espacio libre",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\", hostname=\"$instancia\"}/1000000000",
     "legendFormat": "Espacio disponible"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\", hostname=\"$instancia\"}/1000000000",
     "legendFormat": "Espacio total"
    }
   ]
  },
  {
   "title": "uso de CPU",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (irate(node_cpu_seconds_total{mode=\"idle\", hostname=\"$instancia\"}[2m])) * 100"
    }
   ]
  },
  {
   "title": "Memoria RAM disponible",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{hostname=\"$instancia\"}/1000000"
    }
   ]
  },
  {
   "title": "Uso SWAP",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{hostname=\"$instancia\"} - node_memory_SwapFree_bytes{hostname=\"$instancia\"}) / (node_memory_SwapTotal_bytes{hostname=\"$instancia\"} )) * 100"
    }
   ]
  },
  {
   "title": "Uso de Disco",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "avg_over_time(node_filesystem_size_bytes{hostname=\"$instancia\",fstype=~\"ext4\"}[1m])"
    },
    {
     "expr": "avg_over_time(node_filesystem_avail_bytes{hostname=\"$instancia\",fstype=~\"ext4\"}[1m])"
    },
    {
     "expr": "1-(node_filesystem_avail_bytes{hostname=\"$instancia\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{hostname=\"$instancia\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  { "title": "Historial del Sistema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "uso de Memoria RAM",
   "type": "graph",
   "description": "Memoria total junto con el espacio de memoria disponible",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{hostname=\"$instancia\"}/1000000",
     "legendFormat": "Memoria disponible"
    },
    {
     "expr": "node_memory_MemTotal_bytes{hostname=\"$instancia\"}/1000000",
     "legendFormat": "Memoria total"
    }
   ]
  },
  {
   "title": "tráfico de Red",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\", hostname=\"$instancia\"}[2m])*8",
     "legendFormat": "recibido en \"eth0\""
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\", hostname=\"$instancia\"}[2m])*8",
     "legendFormat": "transmitido en \"eth0\""
    }
   ]
  }
 ]
}